### ISSUE TITLE
ebuild voor synapse?

### ISSUE THREAD

**Issue by noci2012** [PureTryOut/matrix-overlay#1]
Is een ebuild voor de server ook een idee?

**Comment by nado** [comment]
I agree, if you are not interested in doing it yourself, I might find some time to make a PR in September :)

**Comment by PureTryOut** [comment]
Please try to communicate in English @noci2012, even though I understand Dutch perfectly fine of course 😉 

I'd definitely be interested in having an ebuild for it, not so much in writing it myself. If you can find the time you could take a shot @nado.

**Comment by noci2012** [comment]
Ebuild:  not a beauty and not native..., it seems to produce a starting service.
For native install far too many pip entries are missing in portage,
gs-pypi doesn't work AFAICT.

```
# Copyright 1999-2017 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

EAPI=6
PYTHON_COMPAT=( python2_7 )   #{2_7,3_4,3_5} )   #Python 3 gives syntax errors....
DESCRIPTION="A glossy Matrix collaboration server for the web"
HOMEPAGE="https://matrix.org"

inherit eutils #distutils-r1

if [[ ${PV} == "9999" ]]; then
        #inherit git-r3

        SRC_URI=""
        EGIT_REPO_URI="https://github.com/matrix-org/synapse/tarball/master"
        #EGIT_BRANCH="develop"
else
        SRC_URI="https://github.com/matrix-org/synapse/archive/v${PV}.tar.gz -> ${P}.tar.gz"
        KEYWORDS="~amd64 ~x86"
fi

LICENSE="Apache-2.0"
SLOT="0"
IUSE="abi_x86_32 abi_x86_64 doc"
REQUIRED_USE="abi_x86_32? ( !abi_x86_64 )
                        abi_x86_64? ( !abi_x86_32 )"

DEPEND="sys-devel/binutils
                net-libs/nodejs
                virtual/libffi
                dev-python/pip
                dev-python/setuptools
                dev-db/sqlite:3
                dev-python/virtualenv
                dev-libs/libxslt
                dev-python/simplejson
                dev-python/pyyaml
                dev-python/ujson
                dev-python/zope-interface
                dev-python/constantly
                dev-python/incremental
                dev-python/six
                dev-python/attrs
                dev-python/automat
                dev-python/hyperlink
                dev-python/pyasn1
                dev-python/pyasn1-modules
                dev-python/ldap3
                dev-python/ipaddress
                dev-python/enum34
                dev-python/idna
                dev-python/pycparser
                dev-python/cffi
                dev-python/asn1crypto
                dev-python/cryptography
                dev-python/pyopenssl
                dev-python/psutil
                dev-python/olefile
                dev-python/pillow
                dev-python/pynacl
                dev-python/webencodings
                dev-python/html5lib
                dev-python/bleach
                dev-python/netaddr
                dev-python/functools32
                dev-python/jsonschema
                dev-python/markupsafe
                dev-python/decorator
                dev-python/urllib3
                dev-python/chardet
                dev-python/certifi
                dev-python/paste
                dev-python/webob
                dev-python/repoze-who
                dev-python/pycrypto
                dev-python/pytz
                dev-python/python-dateutil
                dev-python/pysaml2
                dev-python/phonenumbers
                "
                #dev-python/bcrypt
                #dev-python/msgpack
                #dev-python/frozendict
                #dev-python/daemonize
                #app-portage/gs-pypi
                #"
RDEPEND="${DEPEND}"
CDEPEND="${DEPEND}"

QA_PREBUILT=" "


#python_test() {
#        # The suite is py2 friendly only
#        if ! python_is_python3; then
#                PYTHONPATH=. "${PYTHON}" ./tests/unit/__init__.py
#        fi
#}

#python_compile_all() {
#        use doc && emake -C docs html
#}

#python_install_all() {
#        use doc && HTML_DOCS=( docs/.build/html/. )
#        distutils-r1_python_install_all
#}

src_unpack () {
        mkdir $S
        virtualenv -p python2.7 $S/synapse
        source $S/synapse/bin/activate
}

src_compile () {
        pip install --upgrade pip
        pip install --upgrade setuptools
        pip install $EGIT_REPO_URI
}

src_install () {
#        distutils-r1_src_install
    insinto /opt/synapse
    cd $S
        #fperms +x synapse/bin/register_new_matrix_user
        #fperms +x synapse/bin/synctl
        #fperms +x synapse/bin/synapse_port_db
        doins -r synapse/include synapse/lib synapse/lib64
        exeinto /opt/synapse/bin
        doexe  synapse/bin/*
        insinto /usr/bin
        dosym /opt/synapse/bin/synapse_port_db /usr/bin/synapse_port_db
        dosym /opt/synapse/bin/synctl /usr/bin/synctl
        dosym /opt/synapse/bin/register_new_matrix_user /usr/bin/register_new_matrix_user
}
```

**Comment by noci2012** [comment]
btw, i have ebuild for these:
                #dev-python/bcrypt
                #dev-python/msgpack
                #dev-python/frozendict
                #dev-python/daemonize

**Comment by nado** [comment]
bcrypt and msgpack are already in the main tree, are they not enough ?

**Comment by noci2012** [comment]
They can be used... but it doesn't actually matter.
Some modules are still missing forcing to use a different non-native build.

This is what does work. esp. the last of the 3 commands.
        pip install --upgrade pip
        pip install --upgrade setuptools
        pip install $EGIT_REPO_URI
this follows the setup method as on the synapse website.
the latter pip-install does download the lot in a subdirectory.

**Comment by noci2012** [comment]
frozendict 
```
# Copyright 1999-2017 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

EAPI=6

PYTHON_COMPAT=( python2_7 python3_{4,5} pypy )

inherit distutils-r1

DESCRIPTION="frozen dictionary"
HOMEPAGE="https://github.com/slezica/python-frozendict https://pypi.python.org/pypi/frozendict/"
SRC_URI="mirror://pypi/${PN:0:1}/${PN}/${P}.tar.gz"

SLOT="0"
LICENSE="Apache-2.0"
KEYWORDS="amd64 ~arm64 ia64 ppc ppc64 x86"
IUSE=""

# The testsuite is not included in the tarball
```

*DEPEND 's not investigated...

**Comment by noci2012** [comment]
daemonize/daemonize-2.4.7.ebuild 
```
# Copyright 1999-2017 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

EAPI=6

PYTHON_COMPAT=( python2_7 python3_{4,5} pypy )

inherit distutils-r1

DESCRIPTION="daemonize toolkit"
HOMEPAGE="https://github.com/thesharp/daemonize https://pypi.python.org/pypi/daemonize/"
SRC_URI="mirror://pypi/${PN:0:1}/${PN}/${P}.tar.gz"

SLOT="0"
LICENSE="Apache-2.0"
KEYWORDS="amd64 ~arm64 ia64 ppc ppc64 x86"
IUSE=""
```

**Comment by PureTryOut** [comment]
With those latter 2 and those others from the main Gentoo repos, it seems you have everything then? Does this trigger a native build?

**Comment by noci2012** [comment]
Hm. not by a longshot..., i stopped looking up modules after the twisted item.

Here is the complete list....
  Downloading https://github.com/matrix-org/synapse/tarball/master
  Downloading frozendict-1.2.tar.gz   <<<--- See above
  Downloading daemonize-2.4.7-py2.py3-none-any.whl     <<<--  see above

  Downloading Twisted-17.9.0.tar.bz2      <<<---- Present 16.6.0-r3, ~17.5.0-r1  [also conflict with required version 13.2.0 for other projects ] 

  Downloading matrix-synapse-ldap3-0.1.3.tar.gz            <<<---- Missing
  Downloading unpaddedbase64-1.1.0-py2.py3-none-any.whl <<<--- missing
  Downloading pydenticon-0.3.1.tar.gz <<<--- Missing
  Downloading pymacaroons_pynacl-0.9.3-py2.py3-none-any.whl  <<<--- Missing
  Downloading signedjson-1.0.0-py2.py3-none-any.whl <<<--- missing
  Downloading matrix-angular-sdk-0.6.8.tar.gz <<<--- missing
  Downloading blist-1.3.6.tar.gz  <<<--- missing
  Downloading canonicaljson-1.0.0-py2.py3-none-any.whl <<<--- missing
  Downloading incremental-17.5.0-py2.py3-none-any.whl <<<--- missing

  Downloading py-bcrypt-0.4.tar.gz   <<<--- Present
  Downloading msgpack-python-0.4.8.tar.gz   <<<--- Present
  Downloading PyYAML-3.12.tar.gz  <<<--- present
  Downloading constantly-15.1.0-py2.py3-none-any.whl <<<--- present
  Downloading Automat-0.6.0-py2.py3-none-any.whl <<<--- present
  Downloading ipaddress-1.0.18-py2-none-any.whl <<<--- present
  Downloading pytz-2017.2-py2.py3-none-any.whl <<<--- present
  Downloading pycrypto-2.6.1.tar.gz <<<--- present
  Downloading Paste-2.0.3-py2-none-any.whl <<<--- present
  Downloading olefile-0.44.zip <<<--- present ~0.44


  Downloading psutil-5.3.1.tar.gz (397kB)  <<<---  present V5.0.1
  Downloading pyOpenSSL-17.3.0-py2.py3-none-any.whl <<<--- Present 162.0
  Downloading service_identity-17.0.0-py2.py3-none-any.whl    <<<--- Present 16.0.0
  Downloading bleach-2.0.0-py2.py3-none-any.whl  <<<--- Present V1.5.0
  Downloading Pillow-4.2.1-cp27-cp27mu-manylinux1_x86_64.whl <<<--- Present 3.4.2-r1
  Downloading ujson-1.35.tar.gz  <<<--- Present 1.33
  Downloading PyNaCl-0.3.0.tar.gz <<<--- present 1.1.2
  Downloading netaddr-0.7.19-py2.py3-none-any.whl <<<--- present 0.7.18
  Downloading jsonschema-2.6.0-py2.py3-none-any.whl <<<--- present 2.5.1-r2
  Downloading Jinja2-2.9.6-py2.py3-none-any.whl  <<<--- present 2.9.5
  Downloading pysaml2-3.0.2.tar.gz <<<--- present 4.0.2-r1
  Downloading pyasn1-0.3.6-py2.py3-none-any.whl  <<<--- present 0.2.3
  Downloading phonenumbers-8.8.2-py2.py3-none-any.whl <<<--- present 8.3.1
  Downloading ldap3-2.3-py2.py3-none-any.whl <<<--- 2.3.3
  Downloading cryptography-2.0.3-cp27-cp27mu-manylinux1_x86_64.whl 
  Downloading six-1.11.0-py2.py3-none-any.whl  <<<--- Present, 1.10, ~1.11
  Downloading attrs-17.2.0-py2.py3-none-any.whl <<<--- present  16.3.0-r1 ~17.2.0
  Downloading pyasn1_modules-0.1.4-py2.py3-none-any.whl  <<<--- present 0.0.8
  Downloading zope.interface-4.4.3-cp27-cp27mu-manylinux1_x86_64.whl <<<--- present 4.3.2
  Downloading simplejson-3.11.1.tar.gz <<<--- present 3.10.0
  Downloading WebOb-1.7.3-py2.py3-none-any.whl  <<<--- present 1.6.3 ~1.7.3
  Downloading certifi-2017.7.27.1-py2.py3-none-any.whl <<<--- present 2017.4.17  ~2017.7.27.1
  Downloading chardet-3.0.4-py2.py3-none-any.whl <<<--- present 2.3.0 ~3.0.4
  Downloading pycparser-2.18.tar.gz <<<--- present 2.14 , ~2.18-r1
  Downloading urllib3-1.22-py2.py3-none-any.whl <<<--- present 1.16, ~1.22
  Downloading webencodings-0.5.1-py2.py3-none-any.whl <<<--- present ~0.5.1
  Downloading asn1crypto-0.23.0-py2.py3-none-any.whl <<<-- present~0.22.0
  Downloading idna-2.6-py2.py3-none-any.whl <<< present 2.5
  Downloading enum34-1.1.6-py2-none-any.whl <<< present 1.1.6
  Downloading python_dateutil-2.6.1-py2.py3-none-any.whl <<<--- 2.4.2-r1 ~2.6.1
  Downloading repoze.who-2.3-py2-none-any.whl <<<--- present 2.2
  Downloading requests-2.18.4-py2.py3-none-any.whl <<<--- present 2.12.5 ~2.18.4
  Downloading decorator-4.1.2-py2.py3-none-any.whl <<<--- present 4.0.10 ~4.1.2
  Downloading MarkupSafe-1.0.tar.gz <<<--- present 0.23 
  Downloading functools32-3.2.3-2.zip <<<--- present 3.2.3
  Downloading cffi-1.11.0-cp27-cp27mu-manylinux1_x86_64.whl  <<<--- present 1.9.1 ~1.10.0
  Downloading html5lib-0.999999999-py2.py3-none-any.whl <<<---- present 0.9999999, ~0.999999999
  Downloading hyperlink-17.3.1-py2.py3-none-any.whl <<<--- present ~17.1.1

So quite some missing, some are present, but mostly with wrong versions...
and a lot of native dev-python modules will generate conflicts because of current requirements.
Besides that this is still an unstable project so anything may move

**Comment by PureTryOut** [comment]
Did you make any progress since? A native build would definitely be awesome to have, and I don't mind packaging the missing dependencies in this overlay if needed.

**Comment by noci2012** [comment]
not really the gcc compiler update causes quite a lot of work atm.
doing emerge -e @world on all systems... and gcc >6.4.0 causes some problems, also 
Gentoo-17 update (needed to be done <6 (now 5) weeks also has some fall out.
on the positive side the dependency on twisted-16.6 is now gone so after the dust settles 
i can continue here.

**Comment by noci2012** [comment]
moot point as it has been removed i see
