### ISSUE TITLE
Dependency missing

### ISSUE THREAD

**Issue by KuroLevin** [PureTryOut/matrix-overlay#4]
riot-web depends on libgconf-2.so.4 that is installed with he package gnome-base/gconf

**Comment by PureTryOut** [comment]
Does this issue still occur with the latest Riot version?

**Comment by KuroLevin** [comment]
yes, it is still happening in version 0.13.3
The error happens when executing riot-web and the exact message is:
riot-web: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory

**Comment by PureTryOut** [comment]
Resolved in 89adcfb28e6d29b0be89f0587973e8a62bf0fc9d
