### ISSUE TITLE
git protocol is insecure error

### ISSUE THREAD

**Issue by JigmeDatse** [PureTryOut/matrix-overlay#5]
When merging nheko, emerge will complain that the git protocol is insecure, and suggests changing to https.  I tested changing git:// to https:// and then updating the digest and it seems to work.  Repoman complains about other things as well (in fact it tells me that there fatal error because of missing metadata.xml file).  Mostly repoman is uncomplaining.

**Comment by PureTryOut** [comment]
Resolved in 027274121cb12944237369189460da7c5ad62081
